/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dataSet.IngredientBuilder;
import mainProgress.MainProgress;

import java.util.ArrayList;

/**
 *
 * @author admin
 */
public class AddIngredient extends javax.swing.JFrame {

    public ArrayList<String> temp = new ArrayList<String>();
    private int check;
    IngredientBuilder ingredientBuilder;

    /**
     * Creates new form enrollment
     */
    public AddIngredient() {
        initComponents();
        check = 0;
        jPanel1_2_1.setVisible(false);
        jPanel1_2_2.setVisible(false);
        jPanel1_2_3.setVisible(false);
        jPanel1_2_4.setVisible(false);
        jPanel1_2_5.setVisible(false);
        jPanel1_2_6.setVisible(false);
        jPanel1_3_1.setVisible(false);
        jPanel1_3_2.setVisible(false);
        jPanel1_3_3.setVisible(false);
        jPanel1_3_4.setVisible(false);
        jPanel1_3_5.setVisible(false);
        jPanel1_3_6.setVisible(false);
        jPanel1_3_7.setVisible(false);
        jPanel1_3_8.setVisible(false);
        jPanel1_3_9.setVisible(false);
        jPanel1_3_10.setVisible(false);
        jPanel4.setVisible(false);
        resultLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        firstPage = new javax.swing.JButton();
        saveItem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Button_1_1 = new javax.swing.JButton();
        Button_1_2 = new javax.swing.JButton();
        jPanel1_3_2 = new javax.swing.JPanel();
        Button_3_2 = new javax.swing.JButton();
        jPanel1_3_1 = new javax.swing.JPanel();
        Button_3_1 = new javax.swing.JButton();
        jPanel1_3_4 = new javax.swing.JPanel();
        Button_3_4 = new javax.swing.JButton();
        jPanel1_3_3 = new javax.swing.JPanel();
        Button_3_3 = new javax.swing.JButton();
        jPanel1_3_5 = new javax.swing.JPanel();
        Button_3_5 = new javax.swing.JButton();
        jPanel1_3_6 = new javax.swing.JPanel();
        Button_3_6 = new javax.swing.JButton();
        jPanel1_3_8 = new javax.swing.JPanel();
        Button_3_8 = new javax.swing.JButton();
        jPanel1_3_7 = new javax.swing.JPanel();
        Button_3_7 = new javax.swing.JButton();
        jPanel1_3_9 = new javax.swing.JPanel();
        Button_3_9 = new javax.swing.JButton();
        jPanel1_3_10 = new javax.swing.JPanel();
        Button_3_10 = new javax.swing.JButton();
        jPanel1_2_3 = new javax.swing.JPanel();
        Button_2_3 = new javax.swing.JButton();
        jPanel1_2_1 = new javax.swing.JPanel();
        Button_2_1 = new javax.swing.JButton();
        jPanel1_2_6 = new javax.swing.JPanel();
        Button_2_6 = new javax.swing.JButton();
        jPanel1_2_4 = new javax.swing.JPanel();
        Button_2_4 = new javax.swing.JButton();
        jPanel1_2_5 = new javax.swing.JPanel();
        Button_2_5 = new javax.swing.JButton();
        jPanel1_2_2 = new javax.swing.JPanel();
        Button_2_2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        resultLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 59, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 215, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 450));
        setResizable(false);

        firstPage.setText("처음으로");
        firstPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPageActionPerformed(evt);
            }
        });

        saveItem.setText("저장");
        saveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItemActionPerformed(evt);
            }
        });

        Button_1_1.setText("냉동");
        Button_1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_1_1ActionPerformed(evt);
            }
        });

        Button_1_2.setText("냉장");
        Button_1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_1_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Button_1_2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                        .addComponent(Button_1_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(Button_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(Button_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
        );

        Button_3_2.setText("jButton11");
        Button_3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_3_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_3_2Layout = new javax.swing.GroupLayout(jPanel1_3_2);
        jPanel1_3_2.setLayout(jPanel1_3_2Layout);
        jPanel1_3_2Layout.setHorizontalGroup(
                jPanel1_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_3_2Layout.setVerticalGroup(
                jPanel1_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_3_1.setText("jButton11");
        Button_3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_3_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_3_1Layout = new javax.swing.GroupLayout(jPanel1_3_1);
        jPanel1_3_1.setLayout(jPanel1_3_1Layout);
        jPanel1_3_1Layout.setHorizontalGroup(
                jPanel1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_3_1Layout.setVerticalGroup(
                jPanel1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_3_4.setText("jButton11");
        Button_3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_3_4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_3_4Layout = new javax.swing.GroupLayout(jPanel1_3_4);
        jPanel1_3_4.setLayout(jPanel1_3_4Layout);
        jPanel1_3_4Layout.setHorizontalGroup(
                jPanel1_3_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_3_4Layout.setVerticalGroup(
                jPanel1_3_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_3_3.setText("jButton11");
        Button_3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_3_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_3_3Layout = new javax.swing.GroupLayout(jPanel1_3_3);
        jPanel1_3_3.setLayout(jPanel1_3_3Layout);
        jPanel1_3_3Layout.setHorizontalGroup(
                jPanel1_3_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_3_3Layout.setVerticalGroup(
                jPanel1_3_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_3_5.setText("jButton11");
        Button_3_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_3_5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_3_5Layout = new javax.swing.GroupLayout(jPanel1_3_5);
        jPanel1_3_5.setLayout(jPanel1_3_5Layout);
        jPanel1_3_5Layout.setHorizontalGroup(
                jPanel1_3_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_3_5Layout.setVerticalGroup(
                jPanel1_3_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_3_6.setText("jButton11");
        Button_3_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_3_6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_3_6Layout = new javax.swing.GroupLayout(jPanel1_3_6);
        jPanel1_3_6.setLayout(jPanel1_3_6Layout);
        jPanel1_3_6Layout.setHorizontalGroup(
                jPanel1_3_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_6)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_3_6Layout.setVerticalGroup(
                jPanel1_3_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_6)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_3_8.setText("jButton11");

        javax.swing.GroupLayout jPanel1_3_8Layout = new javax.swing.GroupLayout(jPanel1_3_8);
        jPanel1_3_8.setLayout(jPanel1_3_8Layout);
        jPanel1_3_8Layout.setHorizontalGroup(
                jPanel1_3_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_8)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_3_8Layout.setVerticalGroup(
                jPanel1_3_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_8)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_3_7.setText("jButton11");

        javax.swing.GroupLayout jPanel1_3_7Layout = new javax.swing.GroupLayout(jPanel1_3_7);
        jPanel1_3_7.setLayout(jPanel1_3_7Layout);
        jPanel1_3_7Layout.setHorizontalGroup(
                jPanel1_3_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_7)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_3_7Layout.setVerticalGroup(
                jPanel1_3_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_7)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_3_9.setText("jButton11");

        javax.swing.GroupLayout jPanel1_3_9Layout = new javax.swing.GroupLayout(jPanel1_3_9);
        jPanel1_3_9.setLayout(jPanel1_3_9Layout);
        jPanel1_3_9Layout.setHorizontalGroup(
                jPanel1_3_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_9)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_3_9Layout.setVerticalGroup(
                jPanel1_3_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_9)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_3_10.setText("jButton11");

        javax.swing.GroupLayout jPanel1_3_10Layout = new javax.swing.GroupLayout(jPanel1_3_10);
        jPanel1_3_10.setLayout(jPanel1_3_10Layout);
        jPanel1_3_10Layout.setHorizontalGroup(
                jPanel1_3_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_10)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_3_10Layout.setVerticalGroup(
                jPanel1_3_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_3_10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_3_10)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_2_3.setText("jButton11");
        Button_2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_2_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_2_3Layout = new javax.swing.GroupLayout(jPanel1_2_3);
        jPanel1_2_3.setLayout(jPanel1_2_3Layout);
        jPanel1_2_3Layout.setHorizontalGroup(
                jPanel1_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_2_3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_2_3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_2_3Layout.setVerticalGroup(
                jPanel1_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_2_3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_2_3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_2_1.setText("jButton11");
        Button_2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_2_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_2_1Layout = new javax.swing.GroupLayout(jPanel1_2_1);
        jPanel1_2_1.setLayout(jPanel1_2_1Layout);
        jPanel1_2_1Layout.setHorizontalGroup(
                jPanel1_2_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_2_1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_2_1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_2_1Layout.setVerticalGroup(
                jPanel1_2_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_2_1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_2_1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_2_6.setText("jButton11");
        Button_2_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_2_6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_2_6Layout = new javax.swing.GroupLayout(jPanel1_2_6);
        jPanel1_2_6.setLayout(jPanel1_2_6Layout);
        jPanel1_2_6Layout.setHorizontalGroup(
                jPanel1_2_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_2_6Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Button_2_6)
                                .addContainerGap())
        );
        jPanel1_2_6Layout.setVerticalGroup(
                jPanel1_2_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_2_6Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Button_2_6)
                                .addContainerGap())
        );

        Button_2_4.setText("jButton11");
        Button_2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_2_4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_2_4Layout = new javax.swing.GroupLayout(jPanel1_2_4);
        jPanel1_2_4.setLayout(jPanel1_2_4Layout);
        jPanel1_2_4Layout.setHorizontalGroup(
                jPanel1_2_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_2_4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Button_2_4)
                                .addContainerGap())
        );
        jPanel1_2_4Layout.setVerticalGroup(
                jPanel1_2_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_2_4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Button_2_4)
                                .addContainerGap())
        );

        Button_2_5.setText("jButton11");
        Button_2_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_2_5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_2_5Layout = new javax.swing.GroupLayout(jPanel1_2_5);
        jPanel1_2_5.setLayout(jPanel1_2_5Layout);
        jPanel1_2_5Layout.setHorizontalGroup(
                jPanel1_2_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_2_5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_2_5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_2_5Layout.setVerticalGroup(
                jPanel1_2_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_2_5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_2_5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_2_2.setText("jButton11");
        Button_2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_2_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_2_2Layout = new javax.swing.GroupLayout(jPanel1_2_2);
        jPanel1_2_2.setLayout(jPanel1_2_2Layout);
        jPanel1_2_2Layout.setHorizontalGroup(
                jPanel1_2_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1_2_2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Button_2_2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_2_2Layout.setVerticalGroup(
                jPanel1_2_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_2_2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Button_2_2)
                                .addContainerGap())
        );

        jTextArea1.setColumns(15);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        resultLabel.setText("resultLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(saveItem))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jPanel1_2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jPanel1_2_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jPanel1_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jPanel1_2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1_2_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jPanel1_2_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(firstPage, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jPanel1_3_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jPanel1_3_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jPanel1_3_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jPanel1_3_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jPanel1_3_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jPanel1_3_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jPanel1_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jPanel1_3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jPanel1_3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jPanel1_3_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel1_2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jPanel1_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jPanel1_2_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel1_2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jPanel1_2_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel1_2_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jPanel1_3_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jPanel1_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jPanel1_3_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jPanel1_3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jPanel1_3_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jPanel1_3_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jPanel1_3_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jPanel1_3_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel1_3_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jPanel1_3_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(firstPage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(saveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(resultLabel))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void firstPageActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        new First().setVisible(true);
    }

    private void saveItemActionPerformed(java.awt.event.ActionEvent evt) {
        if(!jTextArea1.getText().equals("")){
            MainProgress mProgress = new MainProgress();
            ingredientBuilder.name(jTextArea1.getText());
            mProgress.saveIngredient(ingredientBuilder.build());
            this.setVisible(false);
            new First().setVisible(true);
        }
    }

    private void Button_1_1ActionPerformed(java.awt.event.ActionEvent evt) {
        check = 1;
        jPanel1_2_1.setVisible(true);
        jPanel1_2_2.setVisible(true);
        jPanel1_2_3.setVisible(false);
        jPanel1_2_4.setVisible(false);
        jPanel1_2_5.setVisible(false);
        jPanel1_2_6.setVisible(false);

        jPanel1_3_1.setVisible(false);
        jPanel1_3_2.setVisible(false);
        jPanel1_3_3.setVisible(false);
        jPanel1_3_4.setVisible(false);
        jPanel1_3_5.setVisible(false);
        jPanel1_3_6.setVisible(false);

        Button_2_1.setText("육류");
        Button_2_2.setText("가공식품");
        //냉동
        ingredientBuilder = new IngredientBuilder();
        ingredientBuilder.name(jTextArea1.getText());
        ingredientBuilder.keep("냉동");
        resultLabel.setText(ingredientBuilder.build().toString());
    }

    private void Button_1_2ActionPerformed(java.awt.event.ActionEvent evt) {
        check = 2;
        jPanel1_2_1.setVisible(true);
        jPanel1_2_2.setVisible(true);
        jPanel1_2_3.setVisible(true);
        jPanel1_2_4.setVisible(true);
        jPanel1_2_5.setVisible(true);
        jPanel1_2_6.setVisible(true);

        jPanel1_3_1.setVisible(false);
        jPanel1_3_2.setVisible(false);
        jPanel1_3_3.setVisible(false);
        jPanel1_3_4.setVisible(false);
        jPanel1_3_5.setVisible(false);
        jPanel1_3_6.setVisible(false);

        Button_2_1.setText("과일");
        Button_2_2.setText("채소");
        Button_2_3.setText("정육/계란");
        Button_2_4.setText("수산물/건어물");
        Button_2_5.setText("우유/유제품");
        Button_2_6.setText("반찬");
        //냉장
        ingredientBuilder = new IngredientBuilder();
        ingredientBuilder.name(jTextArea1.getText());
        ingredientBuilder.keep("냉장");
        resultLabel.setText(ingredientBuilder.build().toString());
    }

    private void Button_2_1ActionPerformed(java.awt.event.ActionEvent evt) {
        if(check==1){    //냉동
            jPanel1_3_1.setVisible(true);
            jPanel1_3_2.setVisible(true);
            jPanel1_3_3.setVisible(true);
            jPanel1_3_4.setVisible(true);
            jPanel1_3_5.setVisible(false);
            jPanel1_3_6.setVisible(false);

            Button_3_1.setText("냉동돼지고기");
            Button_3_2.setText("냉동소고기");
            Button_3_3.setText("냉동닭고기");
            Button_3_4.setText("냉동오리고기");

            //냉동/육류

        }
        if(check==2){    //냉장
            jPanel1_3_1.setVisible(true);
            jPanel1_3_2.setVisible(true);
            jPanel1_3_3.setVisible(true);
            jPanel1_3_4.setVisible(true);
            jPanel1_3_5.setVisible(true);
            jPanel1_3_6.setVisible(true);


            Button_3_1.setText("사과/배");
            Button_3_2.setText("수박");
            Button_3_3.setText("포도");
            Button_3_4.setText("바나나");
            Button_3_5.setText("오렌지");
            Button_3_6.setText("딸기");
            //냉장/과일
        }
        ingredientBuilder.name(jTextArea1.getText());
        ingredientBuilder.parentCartegory(Button_2_1.getText());
        ingredientBuilder.subCartegory("");
        resultLabel.setText(ingredientBuilder.build().toString());
    }

    private void Button_2_2ActionPerformed(java.awt.event.ActionEvent evt) {
        if(check==1){    //냉동
            jPanel1_3_1.setVisible(true);
            jPanel1_3_2.setVisible(true);
            jPanel1_3_3.setVisible(true);
            jPanel1_3_4.setVisible(false);
            jPanel1_3_5.setVisible(false);
            jPanel1_3_6.setVisible(false);

            Button_3_1.setText("냉동만두");
            Button_3_2.setText("냉동 돈까스");
            Button_3_3.setText("냉동치킨너겟");
            //냉동/가공식품
        }
        if(check==2){    //냉장
            jPanel1_3_1.setVisible(true);
            jPanel1_3_2.setVisible(true);
            jPanel1_3_3.setVisible(true);
            jPanel1_3_4.setVisible(true);
            jPanel1_3_5.setVisible(true);
            jPanel1_3_6.setVisible(true);

            Button_3_1.setText("당근");
            Button_3_2.setText("양파");
            Button_3_3.setText("마늘");
            Button_3_4.setText("감자");
            Button_3_5.setText("고구마");
            Button_3_6.setText("양배추");
            //냉장/채소
        }
        ingredientBuilder.name(jTextArea1.getText());
        ingredientBuilder.parentCartegory(Button_2_2.getText());
        ingredientBuilder.subCartegory("");
        resultLabel.setText(ingredientBuilder.build().toString());
    }

    private void Button_2_3ActionPerformed(java.awt.event.ActionEvent evt) {
        if(check==1){    //냉동
            jPanel1_3_1.setVisible(false);
            jPanel1_3_2.setVisible(false);
            jPanel1_3_3.setVisible(false);
            jPanel1_3_4.setVisible(false);
            jPanel1_3_5.setVisible(false);
            jPanel1_3_6.setVisible(false);
        }
        if(check==2){    //냉장
            jPanel1_3_1.setVisible(true);
            jPanel1_3_2.setVisible(true);
            jPanel1_3_3.setVisible(true);
            jPanel1_3_4.setVisible(true);
            jPanel1_3_5.setVisible(true);
            jPanel1_3_6.setVisible(true);

            Button_3_1.setText("한우");
            Button_3_2.setText("수입 소고기");
            Button_3_3.setText("돼지고기");
            Button_3_4.setText("닭/오리고기");
            Button_3_5.setText("계란");
            Button_3_6.setText("축산간편식");
            //냉장 / 정육/계란
        }
        ingredientBuilder.name(jTextArea1.getText());
        ingredientBuilder.parentCartegory(Button_2_3.getText());
        ingredientBuilder.subCartegory("");
        resultLabel.setText(ingredientBuilder.build().toString());
    }

    private void Button_2_4ActionPerformed(java.awt.event.ActionEvent evt) {
        if(check==1){    //냉동
            jPanel1_3_1.setVisible(false);
            jPanel1_3_2.setVisible(false);
            jPanel1_3_3.setVisible(false);
            jPanel1_3_4.setVisible(false);
            jPanel1_3_5.setVisible(false);
            jPanel1_3_6.setVisible(false);
        }
        if(check==2){    //냉장
            jPanel1_3_1.setVisible(true);
            jPanel1_3_2.setVisible(true);
            jPanel1_3_3.setVisible(true);
            jPanel1_3_4.setVisible(true);
            jPanel1_3_5.setVisible(true);
            jPanel1_3_6.setVisible(true);

            Button_3_1.setText("생선");
            Button_3_2.setText("연체갑각류");
            Button_3_3.setText("회/초밥");
            Button_3_4.setText("김/미역");
            Button_3_5.setText("멸치/건새우");
            Button_3_6.setText("건오징어");
            //냉장 / 수산물/건어물
        }
        ingredientBuilder.name(jTextArea1.getText());
        ingredientBuilder.parentCartegory(Button_2_4.getText());
        ingredientBuilder.subCartegory("");
        resultLabel.setText(ingredientBuilder.build().toString());
    }

    private void Button_2_5ActionPerformed(java.awt.event.ActionEvent evt) {
        if(check==1){   //냉동
            jPanel1_3_1.setVisible(false);
            jPanel1_3_2.setVisible(false);
            jPanel1_3_3.setVisible(false);
            jPanel1_3_4.setVisible(false);
            jPanel1_3_5.setVisible(false);
            jPanel1_3_6.setVisible(false);
        }
        if(check==2){   //냉장
            jPanel1_3_1.setVisible(true);
            jPanel1_3_2.setVisible(true);
            jPanel1_3_3.setVisible(true);
            jPanel1_3_4.setVisible(true);
            jPanel1_3_5.setVisible(true);
            jPanel1_3_6.setVisible(false);

            Button_3_1.setText("우유");
            Button_3_2.setText("요거트");
            Button_3_3.setText("치즈/버터");
            Button_3_4.setText("냉장음료");
            Button_3_5.setText("어린이유제품");
            //냉장 / 우유/유제품
        }
        ingredientBuilder.name(jTextArea1.getText());
        ingredientBuilder.parentCartegory(Button_2_5.getText());
        ingredientBuilder.subCartegory("");
        resultLabel.setText(ingredientBuilder.build().toString());
    }

    private void Button_2_6ActionPerformed(java.awt.event.ActionEvent evt) {
        if(check==1){   //냉동
            jPanel1_3_1.setVisible(false);
            jPanel1_3_2.setVisible(false);
            jPanel1_3_3.setVisible(false);
            jPanel1_3_4.setVisible(false);
            jPanel1_3_5.setVisible(false);
            jPanel1_3_6.setVisible(false);
        }
        if(check==2){   //냉장
            jPanel1_3_1.setVisible(true);
            jPanel1_3_2.setVisible(true);
            jPanel1_3_3.setVisible(true);
            jPanel1_3_4.setVisible(true);
            jPanel1_3_5.setVisible(true);
            jPanel1_3_6.setVisible(true);

            Button_3_1.setText("두부/콩나물");
            Button_3_2.setText("김치");
            Button_3_3.setText("햄/소시지");
            Button_3_4.setText("어묵/단무지");
            Button_3_5.setText("유부/주먹밥");
            Button_3_6.setText("너겟류");
            //냉장 / 반찬
        }
        ingredientBuilder.name(jTextArea1.getText());
        ingredientBuilder.parentCartegory(Button_2_6.getText());
        ingredientBuilder.subCartegory("");
        resultLabel.setText(ingredientBuilder.build().toString());
    }

    private void Button_3_1ActionPerformed(java.awt.event.ActionEvent evt) {
        ingredientBuilder.name(jTextArea1.getText());
        ingredientBuilder.subCartegory(Button_3_1.getText());
        resultLabel.setText(ingredientBuilder.build().toString());
    }

    private void Button_3_2ActionPerformed(java.awt.event.ActionEvent evt) {
        ingredientBuilder.name(jTextArea1.getText());
        ingredientBuilder.subCartegory(Button_3_2.getText());
        resultLabel.setText(ingredientBuilder.build().toString());
    }

    private void Button_3_3ActionPerformed(java.awt.event.ActionEvent evt) {
        ingredientBuilder.name(jTextArea1.getText());
        ingredientBuilder.subCartegory(Button_3_3.getText());
        resultLabel.setText(ingredientBuilder.build().toString());
    }

    private void Button_3_4ActionPerformed(java.awt.event.ActionEvent evt) {
        ingredientBuilder.name(jTextArea1.getText());
        ingredientBuilder.subCartegory(Button_3_4.getText());
        resultLabel.setText(ingredientBuilder.build().toString());
    }

    private void Button_3_5ActionPerformed(java.awt.event.ActionEvent evt) {
        ingredientBuilder.name(jTextArea1.getText());
        ingredientBuilder.subCartegory(Button_3_5.getText());
        resultLabel.setText(ingredientBuilder.build().toString());
    }

    private void Button_3_6ActionPerformed(java.awt.event.ActionEvent evt) {
        ingredientBuilder.name(jTextArea1.getText());
        ingredientBuilder.subCartegory(Button_3_6.getText());
        resultLabel.setText(ingredientBuilder.build().toString());
    }

    // Variables declaration - do not modify
    private javax.swing.JButton Button_1_1;
    private javax.swing.JButton Button_1_2;
    private javax.swing.JButton Button_2_1;
    private javax.swing.JButton Button_2_2;
    private javax.swing.JButton Button_2_3;
    private javax.swing.JButton Button_2_4;
    private javax.swing.JButton Button_2_5;
    private javax.swing.JButton Button_2_6;
    private javax.swing.JButton Button_3_1;
    private javax.swing.JButton Button_3_10;
    private javax.swing.JButton Button_3_2;
    private javax.swing.JButton Button_3_3;
    private javax.swing.JButton Button_3_4;
    private javax.swing.JButton Button_3_5;
    private javax.swing.JButton Button_3_6;
    private javax.swing.JButton Button_3_7;
    private javax.swing.JButton Button_3_8;
    private javax.swing.JButton Button_3_9;
    private javax.swing.JButton firstPage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1_2_1;
    private javax.swing.JPanel jPanel1_2_2;
    private javax.swing.JPanel jPanel1_2_3;
    private javax.swing.JPanel jPanel1_2_4;
    private javax.swing.JPanel jPanel1_2_5;
    private javax.swing.JPanel jPanel1_2_6;
    private javax.swing.JPanel jPanel1_3_1;
    private javax.swing.JPanel jPanel1_3_10;
    private javax.swing.JPanel jPanel1_3_2;
    private javax.swing.JPanel jPanel1_3_3;
    private javax.swing.JPanel jPanel1_3_4;
    private javax.swing.JPanel jPanel1_3_5;
    private javax.swing.JPanel jPanel1_3_6;
    private javax.swing.JPanel jPanel1_3_7;
    private javax.swing.JPanel jPanel1_3_8;
    private javax.swing.JPanel jPanel1_3_9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton saveItem;
    // End of variables declaration
}
