/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import mainProgress.MainProgress;

/**
 *
 * @author admin
 */
public class First extends javax.swing.JFrame {
    MainProgress mProgress = new MainProgress();

    /**
     * Creates new form TTTTT
     */
    public First() {
        initComponents();
        searchHistory.setText("사용한 재료 되돌리기");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nowIngredient = new javax.swing.JButton();
        addIngredient = new javax.swing.JButton();
        searchRecipe = new javax.swing.JButton();
        searchFood = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        searchHistory = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nowIngredient.setText("현재 냉장고 재료 상황");
        nowIngredient.setToolTipText("nowFridgedInient");
        nowIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nowIngredientActionPerformed(evt);
            }
        });

        addIngredient.setText("재료 등록");
        addIngredient.setToolTipText("addIngredient");
        addIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIngredientActionPerformed(evt);
            }
        });

        searchRecipe.setText("레시피 검색");
        searchRecipe.setToolTipText("");
        searchRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRecipeActionPerformed(evt);
            }
        });

        searchFood.setText("현재 재료로 음식 만들기");
        searchFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFoodActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        exit.setText("종료");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("굴림", 0, 36)); // NOI18N
        jLabel2.setText("냉장고를 부탁해");

        searchHistory.setText("검색 기록");
        searchHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(202, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(addIngredient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(nowIngredient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(searchRecipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(searchFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(searchHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(144, 144, 144)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(nowIngredient)
                                .addGap(38, 38, 38)
                                .addComponent(addIngredient)
                                .addGap(38, 38, 38)
                                .addComponent(searchRecipe)
                                .addGap(38, 38, 38)
                                .addComponent(searchFood)
                                .addGap(43, 43, 43)
                                .addComponent(searchHistory)
                                .addGap(37, 37, 37)
                                .addComponent(exit)
                                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void nowIngredientActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        new NowIngredient().setVisible(true);
    }

    private void addIngredientActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        new AddIngredient().setVisible(true);
    }

    private void searchFoodActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        new SearchFood().setVisible(true);
        // TODO add your handling code here:
    }

    private void searchRecipeActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        new SearchRecipe().setVisible(true);
        // TODO add your handling code here:
    }

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);    // TODO add your handling code here:
    }

    private void searchHistoryActionPerformed(java.awt.event.ActionEvent evt) {
        String result = mProgress.restoreRemovedIngredient();
        new CheckDialog(this, true, result).setVisible(true);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton addIngredient;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nowIngredient;
    private javax.swing.JButton searchFood;
    private javax.swing.JButton searchHistory;
    private javax.swing.JButton searchRecipe;
    // End of variables declaration                   
}
