/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author My
 */
import dataSet.Food;
import dataSet.FoodIterator;
import dataSet.FoodSet;
import dataSet.Iterator;
import mainProgress.MainProgress;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
public class SearchFood extends javax.swing.JFrame {
    MainProgress mainProgress;
    DefaultListModel foodList;
    FoodSet foodSet;

    /**
     * Creates new form make
     */
    public SearchFood() {
        initComponents();
        mainProgress = new MainProgress();
        foodList = new DefaultListModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        findFood = new javax.swing.JButton();
        showImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recipeList = new javax.swing.JList<>();
        firstPage = new javax.swing.JButton();
        showRecipe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        findFood.setText("찾기");
        findFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findFoodActionPerformed(evt);
            }
        });

        recipeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recipeListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(recipeList);

        firstPage.setText("처음으로");
        firstPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPageActionPerformed(evt);
            }
        });

        showRecipe.setText("상세레시피");
        showRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRecipeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(findFood, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(showRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstPage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(showImage, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findFood)
                    .addComponent(firstPage)
                    .addComponent(showRecipe))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>                        

    private void findFoodActionPerformed(java.awt.event.ActionEvent evt) {
        foodSet = mainProgress.searchFoodSet(); //요리목록 받아오기
        Iterator iter = foodSet.iterator();
        while (iter.hasNext()){
            Food f = (Food) iter.next();
            foodList.addElement(f.getFoodName());
        }
        recipeList.setModel(foodList);
        recipeList.updateUI();
    }                                        

    private void firstPageActionPerformed(java.awt.event.ActionEvent evt) {                                          
    this.setVisible(false);
    new First().setVisible(true);
    }                                         

    private void recipeListMouseClicked(java.awt.event.MouseEvent evt) {
        String url = foodSet.getFoodImg(recipeList.getSelectedIndex());
        Image image = null;
        try {
            image = ImageIO.read(new URL(url)).getScaledInstance(300,300,Image.SCALE_FAST);
            //image = ImageIO.read(new File("./data/teple.jpg"));
        } catch (MalformedURLException ex) {
            Logger.getLogger(NowIngredient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NowIngredient.class.getName()).log(Level.SEVERE, null, ex);
        }
        showImage.setIcon(new ImageIcon(image));
    }                                       

    private void showRecipeActionPerformed(java.awt.event.ActionEvent evt) {                                           
    this.setVisible(false);
    new RecipeInfo(foodSet.getFoodUrl(recipeList.getSelectedIndex())).setVisible(true);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton findFood;
    private javax.swing.JButton firstPage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> recipeList;
    private javax.swing.JLabel showImage;
    private javax.swing.JButton showRecipe;
    // End of variables declaration                   
}
